# Generated by Django 4.1.2 on 2022-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='buy_date',
        ),
    ]
