# Generated by Django 4.1.2 on 2022-10-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_product_date_remove_product_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Element',
        ),
    ]
